# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome To My Website 
email: Brian.Douglass@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Brian This is my first try at a website so please
  check back often as I add new content. I am currently finishing my 
  final year at The University of Colorado Boulder working on a degree
  in Electrical and Computer Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.brian-douglass.com" # the base hostname & protocol for your site
twitter_username: @brianmdouglass
github_username:  briandouglass

# Build settings
markdown: kramdown
